services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile.web
    image: abeltracker-web:latest
    container_name: web_container
    ports:
      - 80:80
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    image: abeltracker-server:latest
    container_name: server_container
    ports:
      - 3000:3000
