services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile.web
    image: tallies-web:latest
    container_name: tallies-web
    ports:
      - 80:80
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    image: tallies-server:latest
    container_name: tallies-server
    ports:
      - 3000:3000
