name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  build-and-push-web:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web image
        run: |
          docker build \
            --build-arg SERVER_URL=${{ secrets.SERVER_URL }} \
            -t ghcr.io/${{ github.repository_owner }}/tallies-web:latest -f web/Dockerfile.web .
          docker push ghcr.io/${{ github.repository_owner }}/tallies-web:latest

  build-and-push-server:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        run: |
          docker build \
            --build-arg CORS_DOMAINS=${{ secrets.CORS_DOMAINS }} \
            --build-arg PG_HOST=${{ secrets.PG_HOST }} \
            --build-arg PG_PORT=${{ secrets.PG_PORT }} \
            --build-arg PG_USER=${{ secrets.PG_USER }} \
            --build-arg PG_PASSWORD=${{ secrets.PG_PASSWORD }} \
            --build-arg PG_DB=${{ secrets.PG_DB }} \
            -t ghcr.io/${{ github.repository_owner }}/tallies-server:latest \
            -f server/Dockerfile.server .
          docker push ghcr.io/${{ github.repository_owner }}/tallies-server:latest
