name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      web_tag: ${{ steps.web_tag.outputs.tag }}
      server_tag: ${{ steps.server_tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Web Tag
        id: web_tag
        run: echo "tag=$(date +%Y%m%d%H%M%S)-web" >> $GITHUB_OUTPUT

      - name: Generate Server Tag
        id: server_tag
        run: echo "tag=$(date +%Y%m%d%H%M%S)-server" >> $GITHUB_OUTPUT

  build-and-push-web:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push web image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/tallies-web:${{ needs.setup.outputs.web_tag }} -f web/Dockerfile.web .
          docker push ghcr.io/${{ github.repository_owner }}/tallies-web:${{ needs.setup.outputs.web_tag }}

  build-and-push-server:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push server image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/tallies-server:${{ needs.setup.outputs.server_tag }} -f server/Dockerfile.server .
          docker push ghcr.io/${{ github.repository_owner }}/tallies-server:${{ needs.setup.outputs.server_tag }}
