# Build stage
FROM node:20-alpine3.18 AS build-stage
WORKDIR /app

# Copy files needed at the project root
COPY package.json yarn.lock shared-types.ts ./
COPY web/package.json ./web/

# Install all dependencies
RUN yarn install --frozen-lockfile

# Copy web files
COPY web ./web

# Build the Quasar app
WORKDIR /app/web
RUN yarn quasar build

# Production stage
FROM nginx:stable-alpine

# Copy the built app from the build stage
COPY --from=build-stage /app/web/dist/spa /usr/share/nginx/html

# Copy custom nginx configuration
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
